version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: monthly
    labels: [dependabot]

updates:
  - package-ecosystem: github-actions
    directories: [/]
    patterns: ['*']
    cooldown:
      default-days: 14
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directories: ['**/*']
    patterns: ['*']
    cooldown:
      default-days: 14
    multi-ecosystem-group: dependencies
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
