name: deploy
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: NPM Install
        run: npm ci
      - name: Version Package from Tag
        run: npm version "${GITHUB_REF/refs\/tags\//}" --no-git-tag-version
      - name: Build
        run: npm run build
      - name: Package
        run: npm run package
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release-npm
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: npm run release-pypi
